---
version: 2.1

# Tasks definition
jobs:
    test:
        docker:
            # Project's Docker image in Docker Hub
            - image: carlosma7/medauth:latest
        steps:
            - checkout
            # Launch tests using the task manager
            - run: invoke test

# Workflows of CircleCI
workflows:
    test_project:
        jobs:
            - test
