---
version: 2.1

# Tasks definition
jobs:
    test:
        docker:
            # Project's Docker image in Docker Hub
            - image: carlosma7/medauth:latest
        steps:
            - checkout
            # Install dependencies (Invoke, Pytest, and Assertpy)
            - run: pip3 install -r requirements.txt
            # Launch tests using the task manager
            - run: invoke tests

# Workflows of CircleCI
workflows:
    test_project:
        jobs:
            - test
