from .testUsuario import TestUsuario
from .testUsuarioAdmin import TestUsuarioAdmin
from .testUsuarioCliente import TestUsuarioCliente
from .testPoliza import TestPoliza
from .testPrescripcion import TestPrescripcion
from .testAutorizacion import TestAutorizacion
from .testCita import TestCita
from .tipoPoliza import TipoPoliza
from .especialidad import Especialidad
from .moduloExtra import ModuloExtra